# THIS FILE IS AUTOMATICALLY GENERATED
# Project: E:\tmp2\cypress\workspace\490IP1\display-test\display-test.cydsn\display-test.cyprj
# Date: Thu, 04 Jan 2018 15:54:47 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for E:\tmp2\cypress\workspace\490IP1\display-test\display-test.cydsn\TopDesign\TopDesign.cysch
# Project: E:\tmp2\cypress\workspace\490IP1\display-test\display-test.cydsn\display-test.cyprj
# Date: Thu, 04 Jan 2018 15:54:43 GMT
